travis:
  secure:
    BINSTAR_TOKEN: pqXoaPhdvb5sL04YIVp5W2rMR4Qh25pg1BKA23lXyxoHEDoeZeBuMiuv4F+NhfjDf5IUN+lWYIEWlQc1fZRnl8SQl627WLO5n62+ECRk3Nh00ATIIKIdUnHmx0JPcuGGkElZGTE+9UQ1gWSmKMVyXYrN8lmtom/Z20DlrF5tXoHnUo9L+MgA+5/9J0aEDmF+l5Cvq73vKa7cIwuCu7tWlhqIVr0XWHyVGho0n50oRNedHHE/ekCHo8kKHBU2gT20dRlfM7ko1K/a/8JLS+yOTBxwK3QlsSnrHsXGv8+KuzuVM9hm6M5fTsofEKBVcBF6oOO4SgVLdH3z522niuijshmr88Bozb1K/2S/AYdQZm1MrphfjSgw+DLYfKRuPoA8tMf1nJXBRmpLPhkKium9KBEYASTIYn0sSxZIoK83aV9u5D5XkYxRKUbESyxsCnFQK5dYVXzN5U0Cj5ereX6zL4PuiSJU5GrJEdHOyzRXFEnfBrQfCSX9mm4rXT4wjsNeS+51huRXYKWQOlOnUzql9x8ugU5PoGqZaaysYlUlfniCV+AuQqByJXvVqYsPUemeqsLEaqIewQ1Jrz/F+r2PqihfN1RbnODds1I2YP0RJ8otiNyV6dZveqtzQVU3xqWYw2uDXKj3eTlJIszsEI99/PQueS14qSLarYCdjA/QjLI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
